[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Phineas Jensen <phin@zayda.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
